"use client"
import type { Metadata } from "next";
import useStore from "./store";
import { State } from "./store";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import"./global.css"
export default function RootLayout({
  children,
  random
}: Readonly<{
  children: React.ReactNode;
  random: React.ReactNode;
}>) {
  const {lightMode}=useStore() as State
  const style={
    backgroundColor:lightMode?"#B3C8CF":"#222831",
    transition:"0.5s" 

  }
  return (
    <html lang="en">
      <body className="ody" style={style}>{children}</body>
      {random}
    </html>
  );
}
